public enum ENUM_SFXEvent
{
    deckStart,
    dragSound,
    dropSound,
    checkSound,
    GoodSound,
    PlaySound,
    ErrorSound,
    RotateSound,
    SelectSound,
    UnselectSound,
    animalSound,
    dialogueSound,
}

public enum ENUM_SFXAnimals
{
    Jungla_Escarabajo = 0,
    Jungla_Mariposa = 1,
    Jungla_Capibara = 2,
    Jungla_Rana = 3,
    Jungla_Jaguar = 4,
    Jungla_Guacamayo = 5,
    Jungla_Tucan = 6,

    BosqueOtonal_Ciervo = 7,
    BosqueOtonal_Oso = 8,
    BosqueOtonal_Buho = 9,
    BosqueOtonal_Mapache = 10,
    BosqueOtonal_Lince = 11,
    BosqueOtonal_Culebra = 12,
    BosqueOtonal_Ardilla = 13,

    Pradera_Bisonte = 14,
    Pradera_Coyote = 15,
    Pradera_Halcon = 16,
    Pradera_Aguila = 17,
    Pradera_Perdiz = 18,
    Pradera_Conejo = 19,
    Pradera_Serpiente = 20,

    PradoFloral_Abeja = 21,
    PradoFloral_Mariposa = 22,
    PradoFloral_Halcon = 23,
    PradoFloral_Zorro = 24,
    PradoFloral_Liebre = 25,
    PradoFloral_Perdiz = 26,

    RioYManglar_Anaconda = 27,
    RioYManglar_Caiman = 28,
    RioYManglar_Camaron = 29,
    RioYManglar_Delfin = 30,
    RioYManglar_Libelula = 31,
    RioYManglar_Pirana = 32,
    RioYManglar_Salmon = 33,
    RioYManglar_Tortuga = 34,

    TundraNevada_ZorroArtico = 35,
    TundraNevada_BuhoNival = 36,
    TundraNevada_Liebre = 37,
    TundraNevada_Alce = 38,
    TundraNevada_Jabali = 39,
    TundraNevada_Lobo = 40,

    SabanaAfricana_Escarabajo = 41,
    SabanaAfricana_Guepardo = 42,
    SabanaAfricana_Elefante = 43,
    SabanaAfricana_Gacela = 44,
    SabanaAfricana_Nu = 45,
    SabanaAfricana_Hiena = 46,
    SabanaAfricana_Jirafa = 47,
    SabanaAfricana_Leon = 48,
    SabanaAfricana_Avestruz = 49,
    SabanaAfricana_Termita = 50,
    SabanaAfricana_Cebra = 51,

    SabanaAustraliana_Lechuza = 52,
    SabanaAustraliana_Escarabajo = 53,
    SabanaAustraliana_Dingo = 54,
    SabanaAustraliana_Emu = 55,
    SabanaAustraliana_Canguro = 56,
    SabanaAustraliana_Koala = 57,
    SabanaAustraliana_Termita = 58,
    SabanaAustraliana_Varano = 59,

    Montana_Condor = 60,
    Montana_Aguila = 61,
    Montana_Cabra = 62,
    Montana_Llama = 63,
    Montana_Lince = 64,
    Montana_Conejo = 65,

    Okapi = 66,
    Titi_Mono = 67,
    Mushroom = 68
}

public enum ENUM_DialogueEnum
{
    DM_Dialogue1_1 = 1,
    DM_Dialogue1_2,
    DM_Dialogue1_3,
    DM_Dialogue1_4,
    DM_Dialogue1_5,
    DM_Dialogue1_6,
    DM_Dialogue1_7,
    DM_Dialogue1_8,
    DM_Dialogue1_9,
    DM_Dialogue1_10,
    DM_Dialogue1_11,
    DM_Dialogue1_12,
    DM_Dialogue1_13,
    DM_Dialogue2_1,
    DM_Dialogue2_2,
    DM_Dialogue2_3,
    DM_Dialogue2_4,
    DM_Dialogue2_5,
    DM_Dialogue2_6,
    DM_Dialogue2_7,
    DM_Dialogue2_8,
    DM_Dialogue2_9,
    DM_Dialogue2_10,
    DM_Dialogue2_11,
    DM_Dialogue2_12,
    DM_Dialogue2_13,
    DM_Dialogue2_14,
    DM_Dialogue2_15,
    DM_Dialogue2_16,
    DM_Dialogue2_17,
    DM_Dialogue2_18,
    DM_MP_Dialogue3_1,
    DM_MP_Dialogue3_2,
    DM_MP_Dialogue4_1,
    DM_MP_Dialogue4_2,
    DM_MP_Dialogue4_3
}